{
 "title": "KOS Internals",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Number of Workers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kos_agent_worker_count", "legendFormat": "ca @ {{ instance }}" },
    { "expr": "kos_ipam_worker_count", "legendFormat": "ipam @ {{ instance }}" },
    {
     "expr": "kos_subnet_validator_worker_count ",
     "legendFormat": "sv @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Number of CA, By Fabric Name",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kos_agent_fabric_count) by (fabric)",
     "legendFormat": "{{ fabric }}"
    }
   ]
  },
  {
   "title": "KOS git commit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kos_agent_version",
     "legendFormat": "ca {{ git_commit }} @ {{ instance }}"
    },
    {
     "expr": "kos_ipam_version",
     "legendFormat": "ip {{ git_commit }} @ {{ instance }}"
    },
    {
     "expr": "kos_subnet_validator_version",
     "legendFormat": "sv {{ git_commit }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Enqueue Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_workqueue_adds_total[1m])",
     "legendFormat": "{{ name }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Dequeue Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_workqueue_queue_duration_seconds_count[1m])",
     "legendFormat": "{{ name }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Requeue Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_workqueue_retries_total[1m])",
     "legendFormat": "{{ name }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kos_workqueue_depth", "legendFormat": "{{ name }} @ {{ instance }}" }
   ]
  },
  {
   "title": "Subnet Validator Worker Utilization, Summed Over Workers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_workqueue_work_duration_seconds_sum{name=\"sv\"}[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(kos_subnet_validator_subnet_update_latency_seconds_sum[1m])) without (err, statusErr)",
     "legendFormat": "spent on updates"
    },
    {
     "expr": "sum(rate(kos_subnet_validator_live_list_latency_seconds_sum[1m])) without (err)",
     "legendFormat": "spent on live lists"
    }
   ]
  },
  {
   "title": "99th Percentile Subnet Validator Call Out Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_subnet_validator_subnet_update_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ instance }}  status update {{ statusErr }} {{ err }}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(kos_subnet_validator_live_list_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ instance }} live list {{ err }}"
    }
   ]
  },
  {
   "title": "Average Subnet Validator Call Out Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_subnet_validator_subnet_update_latency_seconds_sum[1m]) / rate(kos_subnet_validator_subnet_update_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} status update {{ statusErr }} {{ err }}"
    },
    {
     "expr": "rate(kos_subnet_validator_live_list_latency_seconds_sum[1m]) / rate(kos_subnet_validator_live_list_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} live list {{ err }}"
    }
   ]
  },
  {
   "title": "Rate of Subnet Validator Call Outs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_subnet_validator_subnet_update_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} status update {{ statusErr }} {{ err }}"
    },
    {
     "expr": "rate(kos_subnet_validator_live_list_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} live list {{ err }}"
    }
   ]
  },
  {
   "title": "Subnet Validator Fraction of Live Lists not Needed",
   "type": "graph",
   "description": "When validating a subnet X, the Subnet Validator uses live lists to retrieve potentially conflicting subnets. Sometimes X's status is already up to date hence all processing including the live list was useless. This graph plots the ratio between useless live lists to the total of live lists.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(kos_subnet_validator_duplicate_work_count[1m]) + sum(rate(kos_subnet_validator_subnet_live_vs_conflict_cache_count[1m])) without (mismatch_type)) / ignoring (err) rate(kos_subnet_validator_live_list_latency_seconds_count{err=\"ok\"}[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(kos_subnet_validator_subnet_live_vs_conflict_cache_count[1m]) / ignoring (mismatch_type, err) group_left rate(kos_subnet_validator_live_list_latency_seconds_count{err=\"ok\"}[1m])",
     "legendFormat": "{{ mismatch_type }} mismatch"
    },
    {
     "expr": "sum(rate(kos_subnet_validator_subnet_live_vs_conflict_cache_count[1m])) without (mismatch_type) / ignoring(err) rate(kos_subnet_validator_live_list_latency_seconds_count{err=\"ok\"}[1m])",
     "legendFormat": "total cache mismatches"
    },
    {
     "expr": "rate(kos_subnet_validator_duplicate_work_count[1m]) / ignoring(err) rate(kos_subnet_validator_live_list_latency_seconds_count{err=\"ok\"}[1m])",
     "legendFormat": "subnet status up to date"
    }
   ]
  },
  {
   "title": "Subnet Validator Fraction of Subnet Syncs Ended By Stale Cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_subnet_validator_stale_subnet_work_suppression_count[1m]) / ignoring (name) rate(kos_workqueue_work_duration_seconds_count{name=\"sv\"}[1m])",
     "legendFormat": "stale  / processed"
    }
   ]
  },
  {
   "title": "Subnet Validator 99th Percentile Nbr of Subnets in Live Lists results",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_subnet_validator_number_of_subnets_returned_by_live_list_bucket[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Subnet Validator Avg Nbr of Subnets in Live Lists Results",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_subnet_validator_number_of_subnets_returned_by_live_list_sum[1m]) / rate(kos_subnet_validator_number_of_subnets_returned_by_live_list_count[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "IPAM Worker Utilization, Summed Over Workers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_workqueue_work_duration_seconds_sum{name=\"ipam\"}[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(kos_ipam_attachment_update_latency_seconds_sum[1m])) without (err, statusErr)",
     "legendFormat": "spent on attachment updates"
    },
    {
     "expr": "sum(rate(kos_ipam_ip_lock_latency_seconds_sum[1m])) without (op, err)",
     "legendFormat": "spent on lock ops"
    }
   ]
  },
  {
   "title": "99th Percentile IPAM Call Out Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_attachment_update_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ instance }} status update {{ statusErr }} {{ err }}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_ip_lock_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ instance }} lock {{ op }} {{ err }}"
    }
   ]
  },
  {
   "title": "Average IPAM Call Out Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_ipam_attachment_update_latency_seconds_sum[1m]) / rate(kos_ipam_attachment_update_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} status update {{ statusErr }} {{ err }}"
    },
    {
     "expr": "rate(kos_ipam_ip_lock_latency_seconds_sum[1m]) / rate(kos_ipam_ip_lock_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} lock {{ op }} {{ err }}"
    }
   ]
  },
  {
   "title": "Rate of IPAM Call Outs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_ipam_attachment_update_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} status update {{ statusErr }} {{ err }}"
    },
    {
     "expr": "rate(kos_ipam_ip_lock_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} lock {{ op }} {{ err }}"
    }
   ]
  },
  {
   "title": "Rate of Benefits from Special IPAM Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kos_ipam_anticipation_used_bucket{le=\"1\"}[1m])) without (le) - sum(rate(kos_ipam_anticipation_used_bucket{le=\"0\"}[1m])) without (le)",
     "legendFormat": "clued anticipation @ {{ instance }}"
    },
    {
     "expr": "sum(rate(kos_ipam_anticipation_used_bucket{le=\"2\"}[1m])) without (le) - sum(rate(kos_ipam_anticipation_used_bucket{le=\"1\"}[1m])) without (le)",
     "legendFormat": "unclued anticipation @ {{ instance }}"
    },
    {
     "expr": "rate(kos_ipam_status_used_sum[1m])",
     "legendFormat": "status @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Connection Agent Worker Utilization, Summed Over Workers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_workqueue_work_duration_seconds_sum{name=\"ca\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Fabric utilization, summed over workers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kos_agent_fabric_latency_seconds_sum[1m])) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "99th Percentile Status Update From CA Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 186 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_status_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }} {{ statusErr }} {{ err }}"
    }
   ]
  },
  {
   "title": "Average Status Update From CA Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_attachment_status_latency_seconds_sum[1m]) / rate(kos_agent_attachment_status_latency_seconds_count[1m])",
     "legendFormat": "{{ node }} {{ statusErr }} {{ err }}"
    }
   ]
  },
  {
   "title": "99th Percentile Successful Fabric Create*Port Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 205 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_fabric_latency_seconds_bucket{op=~\"Create.*Ifc\",err!=\"true\"}[1m]))",
     "legendFormat": "{{ op }}@{{ node }}"
    }
   ]
  },
  {
   "title": "90th Percentile Fabric Create*Port Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 214 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(kos_agent_fabric_latency_seconds_bucket{op=~\"Create.*Ifc\"}[1m]))",
     "legendFormat": "{{ op }}@{{ node }} {{ err }}"
    }
   ]
  },
  {
   "title": "Average CreateLocalPort Secs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_fabric_latency_seconds_sum{op=\"CreateLocalIfc\"}[1m])/rate(kos_agent_fabric_latency_seconds_count{op=\"CreateLocalIfc\"}[1m])",
     "legendFormat": "{{ node }} {{ err }}"
    }
   ]
  },
  {
   "title": "Average CreateRemotePort secs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 232 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_fabric_latency_seconds_sum{op=\"CreateRemoteIfc\"}[1m])/rate(kos_agent_fabric_latency_seconds_count{op=\"CreateRemoteIfc\"}[1m])",
     "legendFormat": "{{ node }} {{ err }}"
    }
   ]
  },
  {
   "title": "Average DeleteLocalPort Secs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 241 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_fabric_latency_seconds_sum{op=\"DeleteLocalIfc\"}[1m])/rate(kos_agent_fabric_latency_seconds_count{op=\"DeleteLocalIfc\"}[1m])",
     "legendFormat": "{{ node }} {{ err }}"
    }
   ]
  },
  {
   "title": "Average DeleteRemotePort Secs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 250 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_fabric_latency_seconds_sum{op=\"DeleteRemoteIfc\"}[1m])/rate(kos_agent_fabric_latency_seconds_count{op=\"DeleteRemoteIfc\"}[1m])",
     "legendFormat": "{{ node }} {{ err }}"
    }
   ]
  },
  {
   "title": "Current Number of Local Attachments",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 259 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kos_agent_local_attachments", "legendFormat": "{{ node }}" }
   ]
  },
  {
   "title": "Current Number of Remote Attachments",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 269 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kos_agent_remote_attachments", "legendFormat": "{{ node }}" }
   ]
  }
 ]
}